// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oimsdbfjnqgbxomluzft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbXNkYmZqbnFnYnhvbWx1emZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDk3NDIsImV4cCI6MjA3MDAyNTc0Mn0.qtyMI-POEkyyTq8EQNZwMPJuX1aCkehm9CBX56HOBUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});